[package]
name = "rproxy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
nix = { version = "0.29.0", features = ["net", "socket"] }
tokio = { version = "1.44.2", features = ["io-util", "macros", "rt-multi-thread", "net"] }
